/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Уроки',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'lessons', // Автоматически подтянет все файлы из docs/lessons/
        },
      ],
    },
    {
      type: 'category',
      label: 'Анализ',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'analysis', // Автоматически подтянет все файлы из docs/analysis/
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflow',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'workflows', // Автоматически подтянет все файлы из docs/workflows/
        },
      ],
    },
  ],

  // Можно создать дополнительные сайдбары при необходимости
  // anotherSidebar: [
  //   'doc1',
  //   'doc2',
  // ],
};

export default sidebars;
